version: '3'

services:
  api-nest:
    container_name: ${PROJECT_NAME}-api-nest
    restart: always
    build:
      context: ./api-nest
      dockerfile: Dockerfile.${STAGE}
    volumes:
      - ./api-nest:/home/app
      - /home/app/node_modules
      - /home/app/dist
    ports:
      - 80:3000
