version: '3'

services:
  server-nginx:
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - api-nest
      - client-next
      - db-mysql
    build:
      context: ./server-nginx
      dockerfile: Dockerfile.dev
    volumes:
      # - ./server-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server-nginx/templates:/etc/nginx/templates
    environment:
      API_GUEST_PORT: ${API_GUEST_PORT}
      CLIENT_GUEST_PORT: ${CLIENT_GUEST_PORT}
    ports:
      - 90:80
    networks:
      - network-lnmn

  api-nest:
    container_name: ${PROJECT_NAME}-api-nest
    restart: always
    build:
      context: ./api-nest
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-nest:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    # ports:
    #   - 91:${API_GUEST_PORT}
    networks:
      - network-lnmn

  client-next:
    container_name: ${PROJECT_NAME}-client-next
    restart: always
    build:
      context: ./client-next
      dockerfile: Dockerfile.dev
    volumes:
      - ./client-next:/home/app
      - /home/app/node_modules
    # ports:
    #   - 92:${CLIENT_GUEST_PORT}
    networks:
      - network-lnmn

  db-mysql:
    container_name: ${PROJECT_NAME}-database-mysql
    build:
      context: ./database-mysql
      dockerfile: Dockerfile.dev
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MYSQL_PORT}:3306"
    volumes: 
      - ./database-mysql/data:/var/lib/mysql
      # - ./database-mysql/log:/var/log/mysql
      # - ./database-mysql/config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   - network-lnmn

networks:
  network-lnmn:
    driver: bridge
